# Generated by Django 6.0.6 on 2026-08-10 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stocktransaction_project_and_more'),
        ('procurement', '0001_initial'),
        ('projects', '0002_boq_boqitem'),
        ('sites', '0002_siteconsumption_siteconsumptionitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to='projects.project'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to='sites.site'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='boq_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_items', to='projects.boqitem'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='received_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_items', to='inventory.material'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=50, unique=True)),
                ('request_date', models.DateField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Converted', 'Converted')], default='Draft', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requests', to='projects.boq')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requests', to='projects.project')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requests', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requests', to='sites.site')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='material_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='procurement.materialrequest'),
        ),
        migrations.CreateModel(
            name='MaterialRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('boq_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_items', to='projects.boqitem')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='inventory.material')),
                ('material_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.materialrequest')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='material_request_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_items', to='procurement.materialrequestitem'),
        ),
        migrations.CreateModel(
            name='GoodsReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.goodsreceipt')),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_items', to='procurement.purchaseorderitem')),
            ],
            options={
                'unique_together': {('goods_receipt', 'po_item')},
            },
        ),
    ]
