# Generated by Django 6.0.6 on 2026-08-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_goodsreceipt_project_goodsreceipt_site_and_more'),
        ('projects', '0004_boq_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequest',
            name='request_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='materialrequest',
            unique_together={('project', 'request_number')},
        ),
    ]
