# Generated by Django 6.0.6 on 2026-08-12 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_alter_materialrequest_request_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='action_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_material_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
