# Generated by Django 6.0.6 on 2026-08-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_materialrequest_action_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
