# Generated by Django 6.0.6 on 2026-08-12 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stocktransaction_project_and_more'),
        ('projects', '0004_boq_bill_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMaterialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_qty', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boq_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_stocks', to='projects.boqitem', unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_stocks', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'boq_item')},
            },
        ),
    ]
