# Generated by Django 6.0.6 on 2026-08-12 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_projectmaterialstock'),
        ('projects', '0004_boq_bill_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectmaterialstock',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='projectmaterialstock',
            name='boq_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_stock', to='projects.boqitem'),
        ),
    ]
