# Generated by Django 6.0.6 on 2026-08-11 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stocktransaction_project_and_more'),
        ('projects', '0002_boq_boqitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boqitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='boqitem',
            name='custom_material_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='boq',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='boqitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boq_items', to='inventory.material'),
        ),
    ]
