# Generated by Django 6.0.6 on 2026-08-11 11:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_boqitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boq',
            name='bill_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
