# Generated by Django 6.0.6 on 2026-08-14 06:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_boq_bill_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='boq',
            constraint=models.UniqueConstraint(fields=('project',), name='unique_project_boq'),
        ),
    ]
