# Generated by Django 6.0.6 on 2026-09-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_boq_unique_project_boq'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
