# Generated by Django 6.0.6 on 2026-08-10 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stocktransaction_project_and_more'),
        ('projects', '0002_boq_boqitem'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_date', models.DateField()),
                ('activity', models.CharField(max_length=200)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumptions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_consumptions', to='projects.project')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_consumptions', to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='SiteConsumptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('boq_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_items', to='projects.boqitem')),
                ('consumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sites.siteconsumption')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_items', to='inventory.material')),
            ],
        ),
    ]
